### ISSUE TITLE
Example (WithoutInterupts)  Compile error

### ISSUE THREAD

**Issue by luzel** [igormiktor/arduino-EventManager#1]
D:\arduino-1.0.1\libraries\EventManager\EventManager.cpp: In member function 'boolean EventManager::EventQueue::queueEvent(int, int)':
D:\arduino-1.0.1\libraries\EventManager\EventManager.cpp:484: error: invalid conversion from 'uint8_t' to 'const uint8_t_'
D:\arduino-1.0.1\libraries\EventManager\EventManager.cpp:484: error:   initializing argument 1 of 'void __iRestore(const uint8_t_)'

**Comment by mannkind** [comment]
I'm getting the same error… 

Arduino IDE 1.5 BETA

**Comment by madsbuch** [comment]
I am also suffering under that error

**Comment by igormiktor** [comment]
Fixed.
