### ISSUE TITLE
EVENTMANAGER_LISTENER_LIST_SIZE and EVENTMANAGER_EVENT_QUEUE_SIZE without editing library

### ISSUE THREAD

**Issue by olehs** [igormiktor/arduino-EventManager#14]
How about combining library's header and source file into one .h file?
This would allow setting defines before #include "EventManager.h" in .ino

**Comment by igormiktor** [comment]
No, it will cause link errors for any project that splits code across multiple files which all need to include `EventManager.h`.  More generally, including executable code in header files (except for templates and inline functions) is just a bad thing to do in C/C++.  Just say no :)

**Comment by igormiktor** [comment]
If need to adjust queue sizes, an easy work-around is to include a copy locally of `EventManager.h` and `EventManager.cpp` and edit the `EventManager.h` `#defines` in your local copy.

**Comment by olehs** [comment]
Yes, you are right about multiple source files.

I'm now using [TaskScheduler Library](https://github.com/arkhipenko/TaskScheduler) which is all in one header file. But with Arduino IDE I ususally use multiple .ino files in the project folder rather than split code into multiple .h/.c files.
With this approach there is no problem with compilation.

Anyway, thanks for replay!
