### ISSUE TITLE
How use EventManager along multiple classes

### ISSUE THREAD

**Issue by vlad2005** [igormiktor/arduino-EventManager#15]
Hi!
I try to use EventManager into my project but i have an small problem.
In the main file i create an instance of EventManager like in examples. But i need to add an event to queue from other class. If i instantiate a new EventManager inside that class, then event will not be captured by instance in the main, witch somehow is expected because are different instances of EventManager class. I think that the right term for such as class that have only one instance over entire application is skeleton. Maybe i do something wrong. How i can proceed in this situation?

Thanks for your work!

**Comment by RutgerRauws** [comment]
I think your intuition is right. For my own project I passed a pointer to the main EventManager instance to other classes via an extra argument in their constructors.

I'm not the maintainer of this repository, but I think it would be the way to go.

**Comment by vlad2005** [comment]
Yes. Or maybe instantiate EventManager in one class and then define an public getter method in that class to return instance of EventManager to other classes.

**Comment by vlad2005** [comment]
How to implement this solution with pointers. I'm relative new in C++.
Thanks!

**Comment by RutgerRauws** [comment]
> Or maybe instantiate EventManager in one class and then define an public getter method in that class to return instance of EventManager to other classes.

That wouldn't work (better). As you would have to instantiate the wrapper class as well, defeating its purpose as you then have to pass the wrapper class around. Creating a static getter is also not going to work out, as you want to return the same instance of EventManager and not a new one.

Here's some example code:

**Main.cpp:**

``` c++
#include "EventManager.h"
#include "OtherClass.h"

EventManager *eventManager;
OtherClass *otherClass;

MemberFunctionCallable<OtherClass> ocListener;

void setup()
{
    /*
    * Constructors
    */
    eventManager = new EventManager();
    otherClass = new OtherClass(eventManager);

    /*
    * MFC bindings
     */
    ocListener.mObj = otherClass;
    ocListener.mf = &OtherClass::listener;

    /*
     * Listener bindings
     */
    eventManager->addListener(EventManager::kEventUser0, &ocListener);
}

void loop()
{
    eventManager->processEvent();
    //Do other stuff
}
```

**OtherClass.h:**

``` c++
#ifndef OTHERCLASS_H
#define OTHERCLASS_H

#include "EventManager.h"

class OtherClass
{
  private:
    //Pointer to the eventManager so we can add new events to the event queue
    EventManager *eventManager;

  public:
    /** Constructor
     *  Post: eventManager is assigned to *em
     */
    OtherClass(EventManager *em);

    /** Event listener */
    void listener( int event, int pin );

    void someOtherMethod();
};

#endif /* OTHERCLASS_H */
```

**OtherClass.cpp:**

``` c++
#include "OtherClass.h"

OtherClass::OtherClass(EventManager *em)
    : eventManager(em)
{
    //Construct class
}

void OtherClass::listener(int event, int pin)
{
    //Handle kEventUser0 event
}

void OtherClass::someOtherMethod()
{
    em->queueEvent(EventManager::kEventUser1, 1);
}
```

Please note that I didn't try to compile this code and just renamed some variables and removed methods from an existing project of mine. I assume it works but it at least shows how it works.

**Note:** To use `MemberFunctionCallable`s you should use the [GenericListeners](https://github.com/igormiktor/arduino-EventManager/tree/GenericListeners) branch

**Comment by vlad2005** [comment]
I try to implement this example. Here is my setup (i don't have any compiler error)
I expect to see message "ok" in console but i don't see anything. I use GenericListeners branch.
Thanks for any help!
Main.cpp

```
EventManager *em;
PowerControl pc = PowerControl(em);
void listener( int event, int pin )
{
  Serial.println("ok");
}
GenericCallable<void(int,int)> listenerFreeFunction( listener );

void setup(){
  em = new EventManager();
  em->addListener( EventManager::kEventUser1, &listenerFreeFunction );
}

void loop(){
  em->processEvent();
  pc.check();
}
```

PowerControl.h

```
class PowerControl
{
  private:
    EventManager *eventManager;
  public:
    PowerControl(EventManager *em);
}
```

PowerControl.cpp

```
PowerControl::PowerControl(EventManager *em)
  : eventManager(em)
{

}
void PowerControl::check() {

   eventManager->queueEvent(EventManager::kEventUser1, 0);
}
```

**Comment by igormiktor** [comment]
Hi Vlad,

Rutger is correct (thanks Rutger for answering).  There has to be a single EventManager object that is shared by all who use it.

The simplest, bare-bones way to do this to define the EventManager object globally and then access it everywhere.  No pointers required this way.  For example:

**Main.cpp:**

``` C++
#include "EventManager.h"

EventManager gMyEventMgr;

void myListenerFunction( int eventCode, int eventParam )
{
    // Do something
}

void doSomethingThatPostsEvents()
{
    // This is a plain function, but could be any function within a class
    // Do stuff and then post an event
    gMyEventMgr.queueEvent( EventManager::kEventUser0, 1 );
}

void setup()
{
    // Do stuff with gMyEventMgr
    gMyEventMgr.addListener( EventManager::kEventUser0, &myListenerFunction )
}

void loop()
{
    gMyEventMgr.processEvent();
    doSomethingThatPostsEvents();
}
```

To access it from a separate file use `extern` like so:

**AnotherFile.cpp**

``` C++
#include "EventManager.h"

// This line says to use the same gMyEventMgr defined elsewhere (in Main.cpp in this case)
extern EventManager gMyEventMgr;

class MyClass
{
public:
    void foo()
    { 
        gMyEventMgr.queueEvent(EventManager::kEventUser0, 1);
    }
};
```

The above approach avoids pointers, but hardwires the variable name `gMyEventMgr` and requires `extern` declarations (except for one actual definition, the one in Main.cpp).  This code style is often described as "brittle":  harder to change and doesn't protect you from mistakes.

Rutger's examples show you how to use pointers to achieve the same effect.  Rutger's approach has better style (with pointers hidden safe within classes, although it could be made even "safer" with a singleton class to manager the EventManager object instead of a raw pointer).  However, this code requires additional storage (the object plus a pointer to the object); perhaps more if you use a singleton class), use of the heap (with additional memory overhead), and slower indirect access (via pointers) to the EventManager object.  On normal computers these inefficiencies are of no consequence, but they can actually matter on an Arduino, depending on your application).  

Feel free to ask further questions.  That's the only way we learn :)

Good luck.

**Comment by igormiktor** [comment]
Vlad,

Your code has an error:

``` C++
EventManager *em;
PowerControl pc = PowerControl(em);
```

`em` has no value, so you passed a random value to PowerControl.   You need to pass this value to PowerControl after you've set it.  

Do this instead:

```
EventManager *em;
PowerControl pc = PowerControl;
void listener( int event, int pin )
{
  Serial.println("ok");
}
GenericCallable<void(int,int)> listenerFreeFunction( listener );

void setup(){
  em = new EventManager();
  pc.setEventManager( em );
  em->addListener( EventManager::kEventUser1, &listenerFreeFunction );
}

void loop(){
  em->processEvent();
  pc.check();
}
```

**PowerControl.h**

``` C++
class PowerControl
{
  private:
    EventManager *eventManager;
  public:
    setEventManager( EventManager* em );
}
```

**PowerControl.cpp**

``` C++
PowerControl::setEventManager( EventManager* em )
{
    eventManager = em;
}

void PowerControl::check() {
   eventManager->queueEvent(EventManager::kEventUser1, 0);
}
```

**Comment by vlad2005** [comment]
Thanks for reply!
Your suggestion is obviously most simplest and clear for me. I fact, i want to use EventManager to better organize my code. I have a few classes that interact with each other and I would like to to uncouple them using events. My goal is to have a controller class to listen for all events in the application and execute commands within the logic desired.
For this I would like to implement a class as global listener for various events. Other classes will dispatch events according to various actions specific for each class. Thus decoupled classes between them and will have a kind of hub for events. I'm more familiar with Java witch is somehow more restrictive than C++, so this is why i need some help.

**Comment by igormiktor** [comment]
That decoupling is exactly what EventManager is designed to help with.  A global listener that dispatches events as appropriate is reasonable to implement what you want.

For that design, the only parts of the code that actually need to directly reference the EventManager object are the code where you create the EventManager, set the global listener, and process events.  The global listener doesn't need to directly reference the EventManager.  Neither does the code that post events, because you can hide that in a global function. 

So  one way to implement that would be:

**Main.cpp:**

``` C++
#include "EventManager.h"

EventManager gMyEventMgr;

void postAnEventFunc( int event, int pin )
{
   gMyEventMgr.queueEvent( event, pin );
}

void myGlobalListener( int event, int pin )
{
   // Dispatch events as desired
   // Doesn't need to reference gMyEventMgr
}

GenericCallable<void(int,int)> listenerFreeFunction( myGlobalListener );

void setup()
{
    gMyEventMgr.addListener( EventManager::kEventUser1, &listenerFreeFunction );
}

void loop()
{
    gMyEventMgr.processEvent();
}
```

**PostEventFunc.h**

``` C++
void postAnEventFunc( int event, int pin );
```

**AnotherFile.cpp**

``` C++
#include "PostEventFunc.h"
#include "EventManager.h"

void SomeCode()
{
    postAnEventFunc( EventManager::kEventUser1, 0 );
}
```

This way thegMyEventMgr global object is mostly hidden from the rest of the code.

Of course, there are many ways to implement this.  This is only one particular example.

**Comment by RutgerRauws** [comment]
> Rutger is correct (thanks Rutger for answering).

You're most welcome. Thanks again for helping me out with my own issue, I want to give back a little :wink: My project was a great success thanks to your project!

> Rutger's examples show you how to use pointers to achieve the same effect. Rutger's approach has better style (with pointers hidden safe within classes, although it could be made even "safer" with a singleton class to manager the EventManager object instead of a raw pointer). However, this code requires additional storage (the object plus a pointer to the object); perhaps more if you use a singleton class), use of the heap (with additional memory overhead), and slower indirect access (via pointers) to the EventManager object. On normal computers these inefficiencies are of no consequence, but they can actually matter on an Arduino, depending on your application).

Cannot agree more on the memory part, I didn't think of using one global variable.

**Comment by vlad2005** [comment]
@igormiktor 

> Vlad,
> Your code has an error:

Thanks!
I applied what you suggested and work ok. Now i want to see how implement this in separate class to avoid put listener code in main.

**Comment by igormiktor** [comment]
@RutgerRauws 

> My project was a great success thanks to your project!

I'm glad to hear that!

**Comment by igormiktor** [comment]
@vlad2005 

> Now i want to see how implement this in separate class to avoid put listener code in main.

In the last example I posted, the code for the listener (`myGlobalListener`) can easily be lifted into a separate class that lives in a separate file.  That code doesn't need to reference the global EventManager object.  In fact, it doesn't need to know about the EventManager at all.  So you can have very clean decoupling.

**Comment by vlad2005** [comment]
Ok, i tested different option and i have an new questions.
Most simple form is to use callable objects but need to check for event code to be check inside "operator" function witch is ok when i have an small number of events but not very elegant when have more events.
Second option is to use "callable member functions" witch is more natural. But i like to move all code inside class to clear main.cpp
For example, here:

``` javascript
// A class with a member function we want to use as a listener
    class MyClass
    {
    public:
        void f( int eventCode, int eventParam )
        {
            // Do something with the event
        };
    };

    // Create an instance of this class
    MyClass x;

    // Create the actual listener object that uses x and MyClass::f
    MemberFunctionCallable<MyClass> listenerMemberFunction( &x, &MyClass::f );

    void setup()
    {
        // Add our listener
        gEM.addListener( EventManager::kEventUser0, &listenerMemberFunction );
    }
```

i want that line:

``` javascript
MemberFunctionCallable<MyClass> listenerMemberFunction( &x, &MyClass::f );
```

and

``` javascript
gEM.addListener( EventManager::kEventUser0, &listenerMemberFunction );
```

to be inside MyClass. It's possibil to do that?

**Comment by vlad2005** [comment]
This is what i try'it for moment, but not work (no compiler error). I try'it to move any addlistener from main to class that implement listener.
Main.cpp

``` javascript
GateControl gc = GateControl(); //my listener class
EventManager em = EventManager(); 
PowerControl pc = PowerControl();

void setup(){
  em = gc.getEventManager();
  pc = gc.getPowerControl();
}

void loop(){
  em.processEvent();
  pc.check();
}
```

GateControl.h

``` javascript
class GateControl : public EventListener
{
  private:
    EventManager *_em;
    PowerControl pc = PowerControl();

 public:
    EventManager getEventManager();
    PowerControl getPowerControl();
    void operator()(int eventCode, int eventParam);
}
```

GateControl.cpp

``` javascript
GateControl::GateControl(){
    _em = new EventManager();
    pc.setEventManager( _em );
    _em->addListener( EventManager::kEventUser1, this );
};

void GateControl::operator()(int eventCode, int eventParam) {
  Serial.println("okt");
};

EventManager GateControl::getEventManager() {
    return *_em;
};

PowerControl GateControl::getPowerControl() {
    return pc;
}
```

In PowerControl class, nothing changed.

**Comment by igormiktor** [comment]
One error is that the code is setting `em` and `pc` multiple times.  

Here:

```
GateControl gc = GateControl(); //my listener class
EventManager em = EventManager(); 
PowerControl pc = PowerControl();
```

and again here

```
void setup(){
  em = gc.getEventManager();
  pc = gc.getPowerControl();
}
```

If you simply walk the your code as it would execute (pretend you are the computer and walk through it in sequence) you will see this problem right away.  I think there are other logic problems also, but I didn't follow the entire logic.

Also, design is obviously your choice, but why build EventManager into your listener class -- your listener class doesn't need to know at all about the EventManager.  It can be completely separated from it.  Really the only code that needs to even know EventManager exists is the setup() function and the loop() function.  

I offer the thought that decoupling and decomposition (at least in C++) is not about putting everything inside classes, but rather about code separation -- if things don't need to reference each other, they shouldn't:  Don't make PowerControl know about EventManger (via `em`), instead simply have it call the function `postAnEventFunc()` (see my last example code, obviously name it as you wish).  Make GateControl a class that knows nothing about EventManager, instead GateControl simply deals with the event arguments (eventCode and eventParam).  The EventManager object can be a global (or pointer if you prefer) that lives in the same file as `setup()` and `loop()` and no other code needs to even know it exists.

Looking at your code, you have code to hide the EventManager object in GateControl, but the only purpose is to pass the EventManager back to `setup()` and `loop()`.  Why bother with all that complication?

Again, just thoughts for what it is worth...

**Comment by igormiktor** [comment]
>  i want that line:
> 
> MemberFunctionCallable<MyClass> listenerMemberFunction( &x, &MyClass::f );
> 
> and
> 
> gEM.addListener( EventManager::kEventUser0, &listenerMemberFunction );
> 
> to be inside MyClass. It's possibil to do that?

You probably can, but in C++ you must pay careful attention to the lifespan of the variables.  Both `x` and `listenerMemberFunction` have to be objects that have lifespans as long as program execution lasts.  They can't be local variables.  If they are member variables, the object they are part of has to live for the entire time the program is executing.  This will take some careful thinking (which I have not done).

There may be some syntax rule in C++ that prevents this, but I don't think so.  But I'm not a C++ language lawyer :)

**Comment by vlad2005** [comment]
You are right. I work mostly with events in Actionscript (Flex) and Java and come with mentality from this superior languages. Also I have no experience with pointers. Obviously C++ and especially working with micro controllers are very different. I will reread entire topic and will implement best solution for me.

Thanks for you effort!

**Comment by vlad2005** [comment]
I have an last question!
In my application, where class GateControl act as an hub for all events, witch solution is recommended to instantiate EventManager and GateControl class? As pointers or non-pointer.
Thanks!

**Comment by igormiktor** [comment]
Depends if you have to pass it around (as a return argument of a function, for example).  If you don't need to share it, keep it as a non-pointer. If your design requires you to share it, then it will have to be a pointer.

**Comment by vlad2005** [comment]
Ok, thanks!
EventManager will be shared along multiple class that dispatch specific
events. So i will keep as pointer.
