### ISSUE TITLE
Won't compile for esp32

### ISSUE THREAD

**Issue by michox** [igormiktor/arduino-EventManager#17]
Hi, I wanted to use this for an esp32 which is a fairly widely used microcontroller nowdays but I get the following error log when compiling:
`lib\EventManager\EventManager.cpp:153:2: error: #error "Unknown microcontroller:  Need to implement class SuppressInterrupts for this microcontroller."
 #error "Unknown microcontroller:  Need to implement class SuppressInterrupts for this microcontroller."
  ^
lib\EventManager\EventManager.cpp: In constructor 'EventManager::EventQueue::EventQueue()':
lib\EventManager\EventManager.cpp:543:31: error: 'kEventNone' is not a member of 'EventManager'
         mEventQueue[i].code = EventManager::kEventNone;
                               ^
lib\EventManager\EventManager.cpp: In member function 'boolean EventManager::EventQueue::queueEvent(int, int)':
lib\EventManager\EventManager.cpp:574:5: error: 'SuppressInterrupts' was not declared in this scope
     SuppressInterrupts  interruptsOff;      // Interrupts automatically restored when exit block
     ^
lib\EventManager\EventManager.cpp: In member function 'boolean EventManager::EventQueue::popEvent(int*, int*)':
lib\EventManager\EventManager.cpp:624:5: error: 'SuppressInterrupts' was not declared in this scope
     SuppressInterrupts  interruptsOff;      // Interrupts automatically restored when exit block
     ^
lib\EventManager\EventManager.cpp:632:43: error: 'kEventNone' is not a member of 'EventManager'
     mEventQueue[ mEventQueueHead ].code = EventManager::kEventNone;`
Is there any chance that the esp32 would get Interrupt support? thats really the onyl usefull feature that I would see in this library for my project...

**Comment by igormiktor** [comment]
I will look at it this weekend.  In theory it is easy to create a version for esp32.  The "hard" part is tracking down answers to the following questions for esp32:

1. How to read the current state of interrupt status (on/off, for each interrupt type if they can be individually controlled).
2. How turn off all interrupts.
3. How to restore a previous state of interrupt status (i.e., reset the prior status read at #1)

This info can sometimes be time consuming to research.  If you have time to dig around for answers for the esp32, it would help and be much appreciated.

**Comment by elguiri** [comment]
Hi @igormiktor 

Thanks very much for your library. Arduino on ESP32 (which is dual core) sits on top of FreeRTOS, so multitasking and multicore issues need to be considered. Whilst your library has SuppressInterrupts (checking the current state), in ESP32 a more general approach to making an atomic block is required, using a mutex. The mutex provides for both task and core exclusivity. The documentation [here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/freertos-smp.html#critical-sections-disabling-interrupts) explains why it is not enough to disable interrupts.

The following include is required (and as an example I'm showing the processor type to be checked for)...
```
#if defined ( ESP32 )
#include <freertos/portmacro.h>
```
A critical section is started with...
```
portMUX_TYPE mux = portMUX_INITIALIZER_UNLOCKED;
portENTER_CRITICAL(&mux);
```
And ended with...
```
portEXIT_CRITICAL(&mux);
```

**Comment by igormiktor** [comment]
Hi @elguiri,

Thanks, I got that impression skimming some of the docs about a couple months ago. I thought about it then and it would require significant modifications to the library to make use of mutexes.  In fact, I would be inclined to redesign the API in a mutex environment.  

So I regret to say, I won't be implementing an esp32/FreeRTOS version of this library.  If anyone cares to take this on, I'll certainly consider a pull request.  

Sorry.

**Comment by elguiri** [comment]
Unless I'm missing something it would be as simple as the code addition below? The rest of the ESP32 FreeRTOS implementation is hidden away under Arduino anyway, so it's not necessary to have any other code changes. Would you want to change the name of SuppressInterrupts to a more general AtomicBlock for example?

```
#elif defined( ESP32 )
#include <freertos/portmacro.h>
    class SuppressInterrupts
    {
    public:
        SuppressInterrupts()
        {
            portENTER_CRITICAL(&mMux);
        }

        ~SuppressInterrupts()
        {
            portEXIT_CRITICAL(&mMux);
        }

    private:
        static portMUX_TYPE mMux = portMUX_INITIALIZER_UNLOCKED;
    };
#else
```

Edited... a couple of times!!! Added static to the declaration of the mutex and also moved the initialisation to the declaration!

**Comment by igormiktor** [comment]
I have no way to test it, but I strongly suspect that mMux should only be assigned once (at start-up, or first time used).  That's the common way for other mutexes to work (the single instance has to be shared by all).  But I don't know FreeRTOS.  The code appears to create a new instance of mMux everytime (but perhaps portMUX_INITIALIZER_UNLOCKED returns a single global object under the hood).  

If you have an esp32 give it a try and stress test it.  If it works, send me a pull request.

**Comment by elguiri** [comment]
> The code appears to create a new instance of mMux everytime

Apologies, I think my edit and your post overlapped, I'd added a static to the declaration of the mutex. I'll do some testing indeed.

Edit... and just moved the initialisation as well. A good code example is [here](https://github.com/espressif/esp-idf/blob/release/v3.2/components/ethernet/emac_main.c) (see the use of _g_emac_mux_).

**Comment by elguiri** [comment]
```
#include <Arduino.h>

#ifndef ESP32
#error This code is designed to run on the ESP32 Arduino platform
#endif

// Using the master branch of arduino-EventManager
// https://github.com/igormiktor/arduino-EventManager/tree/master
#include <EventManager\EventManager.h>

// Using the ESP32TimerInterrupt library
// https://github.com/khoih-prog/ESP32TimerInterrupt
#include <ESP32TimerInterrupt.h>

EventManager eventManager;

struct Pins
{
    int pinNumber;
    int pinState;
};

Pins pins[2] = { { LED_BUILTIN, LOW }, { 4, LOW } };

#define TIMER0_INTERVAL_MS 100UL
ESP32Timer interruptTimer0(0);

// IRAM_ATTR is required to place the handler in the right area of memory
void IRAM_ATTR interruptHandler(void) {

    static int oddEven = 0;

    eventManager.queueEvent( EventManager::kEventUser0, 0 );

    if ( !oddEven ) {
        eventManager.queueEvent( EventManager::kEventUser0, 1 );
    }

    ++oddEven;
    oddEven %= 3;
}

void listener( int event, int pin ) {

    pins[pin].pinState = pins[pin].pinState ? 0 : 1;
    digitalWrite( pins[pin].pinNumber, pins[pin].pinState ? HIGH : LOW );
}

void setup() {

    Serial.begin( 115200 );
    Serial.println( "Entering setup()" );

    pinMode( pins[0].pinNumber, OUTPUT );
    pinMode( pins[1].pinNumber, OUTPUT );

    eventManager.addListener( EventManager::kEventUser0, listener );

    interruptTimer0.attachInterruptInterval(TIMER0_INTERVAL_MS * 1000UL, interruptHandler);
}

void loop() {

    eventManager.processEvent();
}
```

**Comment by elguiri** [comment]
Note the use of IRAM_ATTR for an interrupt handler under ESP32. I changed the timer library to one suitable for ESP32 as well (and have it running at 100ms interval).

**Comment by elguiri** [comment]
Note I've just updated the code example above with comments on the includes

**Comment by igormiktor** [comment]
Thanks, @elguiri 

Both pull requests merged, and example files for ESP32 added.  Much appreciate you doing all heavy lifting on this!

**Comment by elguiri** [comment]
@michox 

ESP32 versions (including example code due to specific nature of IRAM_ATTR placement) are now available on the master and GenericListeners branches
