### ISSUE TITLE
Example (WithInterrupts)

### ISSUE THREAD

**Issue by komlev** [igormiktor/arduino-EventManager#2]
Arduino: 1.5.4 (Windows 7), Board: "Arduino Uno"

Arduino\libraries\EventManager\EventManager.cpp: In member function 'boolean EventManager::EventQueue::queueEvent(int, int)':
Arduino\libraries\EventManager\EventManager.cpp:484: error: invalid conversion from 'uint8_t' to 'const uint8_t_'
Arduino\libraries\EventManager\EventManager.cpp:484: error:   initializing argument 1 of 'void __iRestore(const uint8_t_)'

**Comment by dkgrieshammer** [comment]
got the same error, UNO and Mega using OSX Mavericks

**Comment by igormiktor** [comment]
Fixed, due to newer Arduino libs
