### ISSUE TITLE
Support for Arduino MKR Zero

### ISSUE THREAD

**Issue by pboguslawski** [igormiktor/arduino-EventManager#20]
Hello,

When building project in PlatformIO for

```
Arduino MKR Zero
[env:arduino_mkr_zero]
platform = atmelsam
board = mkrzero

```
with arduino-EventManager (GenericListeners branch), an error occurs:

`lib/arduino-EventManager/EventManager/EventManager.cpp:180:2: error: #error "Unknown microcontroller:  Need to implement class SuppressInterrupts for this microcontroller."`

There is no `ARDUINO_ARCH_SAMD` ifdef in

https://github.com/igormiktor/arduino-EventManager/blob/GenericListeners/EventManager/EventManager.cpp#L43

Other projects use it for Arduino Zero:

https://github.com/KONNEKTING/KonnektingDeviceLibrary/blob/develop/examples/Communication_test/Communication_test.ino#L32

Can you please add support for mkrzero board to arduino-EventManager?

Checked that using same settings as for SAM, i.e. changing

```
-#elif defined( SAM )
+#elif defined( ARDUINO_ARCH_SAMD )
```

in

https://github.com/igormiktor/arduino-EventManager/blob/GenericListeners/EventManager/EventManager.cpp#L71

allows building for mkrzero without errors but not sure if this is correct solution for this board.

**Comment by pboguslawski** [comment]
According to

https://www.arduino.cc/en/Main/ArduinoBoardMKRZero

Arduino MKR Zero is powered by Atmel’s SAMD21 MCU, which features a 32-bit ARM Cortex® M0+ core.

According to

https://forum.arduino.cc/index.php?topic=457720.0
https://developer.arm.com/documentation/dui0662/b/The-Cortex-M0--Processor/Programmers-model/Core-registers?lang=en

```
__disable_irq()
__enable_irq()
PRIMASK

```

play the same role as for SAM. Seems that for adding support for SAMD changing

-#elif defined( SAM )
+#elif defined( ARDUINO_ARCH_SAM ) || defined( ARDUINO_ARCH_SAMD )

will be sufficient.

Please verify and consider fixing.

**Comment by elguiri** [comment]
Hi Pawel

As a workaround not involving editing the library, have you tried defining SAM in your [platformio.ini](https://docs.platformio.org/en/latest/projectconf/section_env_build.html#build-flags) file...

`build_flags = -D SAM`

Best regards

**Comment by pboguslawski** [comment]
This may work for arduino-EventManager but SAM and SAMD are different platforms in PlatformIO...

https://github.com/arduino/ArduinoCore-samd
https://github.com/arduino/ArduinoCore-sam

...and this hack may break something in other libs so I prefer to fix

```
-#elif defined( SAM )
+#elif defined( ARDUINO_ARCH_SAM ) || defined( ARDUINO_ARCH_SAMD )
```

...arduino-EventManager (give me know its wrong please).

**Comment by pboguslawski** [comment]
BTW: didn't notice any issues with above fix on Arduino MKR Zero.

**Comment by pboguslawski** [comment]
BTW: What you think about passing pointers as eventParam not int? This would allow one to pass different stuff using events, i.e. pointers to objects, floats, arrays, etc. Now one must use ticks to pack float for example to pass it using eventParam.

**Comment by elguiri** [comment]
> -#elif defined( SAM )
> +#elif defined( ARDUINO_ARCH_SAM ) || defined( ARDUINO_ARCH_SAMD )

The above would be a breaking change if somebody was relying on SAM rather than ARDUINO_ARCH_SAM being defined. It may be more correct to do...

> -#elif defined( SAM )
> +#elif defined( SAM ) || defined( ARDUINO_ARCH_SAM ) || defined( ARDUINO_ARCH_SAMD )

You could submit a pull request for @igormiktor to consider (note I did this for the ESP32 addition if you check the closed pull requests and issues).

**Comment by elguiri** [comment]
> BTW: What you think about passing pointers as eventParam not int? This would allow one to pass different stuff using events, i.e. pointers to objects, floats, arrays, etc. Now one must use ticks to pack float for example to pass it using eventParam.

That might be a different library! Passing as int is relatively safe as it will be on the stack. Anything involving pointers to objects is going to involve memory management of those objects, and that's not for everybody.

I've not looked too closely at the code, but if you really wanted to use pointers could you cast the int that is available to a pointer?

**Comment by igormiktor** [comment]
@pboguslawski I do not have any of the hardware you are using, so I cannot verify or test any of it.  You are welcome to send me a pull request, but you need to test it on your hardware and (as @elguiri points out) please do not do things that would break existing code.

I will not change the event parameter.  Keeping it int is essential for time and space guarantees on the tightly constrained AVR systems that are the primary target of this library.  However, look at the branch "GoodnatureBeacon" -- this branch is designed to make it easy (with a #define) to set the event parameter to a different type.  The GoodnatureBeacon branch, however, is **UNTESTED** (the original requestor never provided any feedback).  I have no need for event parameters other than int, so I never tested it.  See if that branch works for you or if not perhaps provides a starting point for you to fork your own version of this library.

**Comment by pboguslawski** [comment]
> You are welcome to send me a pull request

PRs sent:
- GenericListeners: https://github.com/igormiktor/arduino-EventManager/pull/21
- master: https://github.com/igormiktor/arduino-EventManager/pull/22

>  but you need to test it on your hardware 

Checked on Arduino MKR Zero that with...

```
#include <Arduino.h>

void buttonPressHandler() {
    digitalWrite(2, !digitalRead(4));
}

void setup() {
    pinMode(1, OUTPUT);    
    pinMode(2, OUTPUT);
    pinMode(4, INPUT_PULLUP);

    // Turn ON LED2 on BUTTON4 press.
    attachInterrupt(digitalPinToInterrupt(4), buttonPressHandler, CHANGE);

    __enable_irq();
    //__disable_irq();
  
    // Turn ON LED1 if interrupts are DISABLED.
    if (__get_PRIMASK() == 0) {
      digitalWrite(1, LOW); 
    }
    else {
      digitalWrite(1, HIGH);
    }  
}

void loop() {  
}
```
LED1 is turned off and button4 press turns ON LED2 (=interrupt status is read ok and interrupts are enabled) and after change

```
//    __enable_irq();
  __disable_irq();
```
LED1 is turned on and button4 pressed does not turn ON LED2  (=interrupt status is read ok and interrupts are disabled).

So it works just like for SAM in current code.

**Comment by igormiktor** [comment]
Look good.  Will double check on my hardware tomorrow.

One question (for both @pboguslawski and @elguiri):  any reason to not also add in 
`defined( ARDUINO_ARCH_SAM )`
so the line would read:
`#elif defined( SAM ) || defined( ARDUINO_ARCH_SAM ) || defined( ARDUINO_ARCH_SAMD )`

**Comment by pboguslawski** [comment]
> any reason to not also add in defined( ARDUINO_ARCH_SAM )

According to your request

> but you need to test it on your hardware and (as @elguiri points out) please do not do things that would break existing code.

I didn't touch SAM stuff because I don't have such hardware to test it. Tested only Arduino MKR Zero (SAMD) thats why only `ARDUINO_ARCH_SAMD` was added. Feel free to test and extend it further.

Thank you for great lib!

Regards,
Paweł
