### ISSUE TITLE
Wish

### ISSUE THREAD

**Issue by fbacker** [igormiktor/arduino-EventManager#5]
Be able to use multiple variable types. Now you can only send events with int parameter. 

A good thing would be to be able to send any kind of value.

Example:
eventManager->queueEvent(EventType::Log, "My value");
eventManager->queueEvent(EventType::VALUE1, 1);

or maybe:
eventManager->queueEvent(EventType::Log, EventItem<String>("My value"));
eventManager->queueEvent(EventType::VALUE1, EventItem<String>(1));

**Comment by igormiktor** [comment]
Given limited resources, hard to do flexibly on an Arduino.  We'd have to reserve room for the largest possible type size.  Given limited RAM, I wouldn't want to double the memory footprint of the EventManager just for perhaps storing event value types that are double-word sized.  Nor do I want to use dynamic memory allocation (lots of reasons to avoid this on AVRs).  

If you just want alternate types that are the same size as int (word-sized), then that just takes some overloading of existing functions that internally casts to/from int.  If you build such a patch, I would be open to it.

**Comment by fbacker** [comment]
Guessed that was the reason. Not used to code for small footprint, more for
flexibility. But no issue to work around and always use int.

And by the way. Love the plugin =)
